#!/bin/bash

d=$PWD

list="bashrc aliases emacs emacs.d gitconfig tmux vimrc"

for i in $list; do
    cmd="ln -s $d/$i $HOME/.$i"
    echo -n "Linking ./$i: "
    $cmd && echo "Done."
done

if [ ! -e $HOME/.vim ]; then
    ln -sf $d/vim $HOME/.vim
    mkdir $HOME/.vim/bundle
    git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
else
    echo .vim directory or link exists. Aborting.
fi

