#!/bin/bash

d=$PWD

list="bashrc aliases emacs emacs.d gitconfig tmux vim vimrc"

for i in $list; do
    cmd="ln -s $d/$i $HOME/.$i"
    echo -n "Linking ./$i: "
    $cmd && echo "Done."
done

if [ ! -e ~/.vim/bundle/vim-bundler ]; then
    mkdir ~/.vim/bundle
    cd ~/.vim/bundle
    git clone git://github.com/tpope/vim-bundler.git
fi

