#!/bin/bash

d=$PWD

list="bashrc aliases emacs emacs.d gitconfig tmux vimrc"

for i in $list; do
    cmd="ln -s $d/$i $HOME/.$i"
    echo -n "Linking ./$i: "
    $cmd && echo "Done."
done

if [ ! -e ~/.vim/bundle/vim-bundler ]; then
    ln -sf $d/vim $HOME/.vim
    mkdir $HOME/.vim/bundle
    cd $HOME/.vim/bundle
    git clone git://github.com/tpope/vim-bundler.git
fi

